name: Release NodeJS app

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: rchou97
          password: dckr_pat_Q4ZnihaOJBJ2tomzLgxCQJx6STY
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: Rchou97/express-app:latest
